### PR TITLE
Feat execute macros from ship positions

### PR DESCRIPTION
**Pull request by Kampfzwerg42**
* **Please check if the PR fulfills these requirements**
- [x] We use semantic versioning (https://github.com/semantic-release/semantic-release to be specific), so follow https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature: allow macro execution from a ship position
feature: add a select list to select the component to use in the ship position configuration

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by marvin9257** [comment]
The original ship position code by @jonepatr included an option to run macros.  However, we removed that as an option as it caused security issues - players could run macros with a GM privileges.  I haven't tried this PR, but how does it work from a player account?  Thanks.

**Comment by Kampfzwerg42** [comment]
"run with a GM privilege" so that game.user.isGM is true?(I dont think this is normally possible to achieve since the user of the game variable is not that easy changeable... I could add a macro.canExecute() check to check if the user is allowed to execute that macro...)

**Comment by marvin9257** [comment]
That sounds like a good check to make.  After you are done, I'll try to create a macro to see whether I can change data for an actor I don't own.

**Comment by xdy** [comment]
If it's changed so that it can only load the macros from a compendium I'd be less wary of it.
That way the GM has to be involved in some way for them to become available. (Whether by adding them himself to a compendium, or by granting trusted players permission to add macros to compendiums.)

**Comment by xdy** [comment]
I'm sure someone will manage to shoot themself in the foot by trusting someone they shouldn't, but at least this way there's some friction.
This is a very nice tool to have, but, it's a sharp tool that can potentially cause a lot of damage, so I'd err on the side of caution.
Hopefully not affecting the machine foundry runs on, but losing a world can be bad enough.

**Comment by marvin9257** [comment]
Sorry, one more consideration.  It would also be good to add a check that user.isTrusted or user.isGM.  That would force the GM to elevate folks level to use the feature.  Right now, I think that script macro permission is enabled by default.

**Comment by Kampfzwerg42** [comment]
> Sorry, one more consideration. It would also be good to add a check that user.isTrusted or user.isGM. That would force the GM to elevate folks level to use the feature. Right now, I think that script macro permission is enabled by default.

But they shouldn't be able to do more or less harm as with 'normal' foundry macros anyway...

**Comment by marvin9257** [comment]
> > Sorry, one more consideration. It would also be good to add a check that user.isTrusted or user.isGM. That would force the GM to elevate folks level to use the feature. Right now, I think that script macro permission is enabled by default.
> 
> But they shouldn't be able to do more or less harm as with 'normal' foundry macros anyway...

Yeah...I just tried with some simple script macros.  FVTT only lets you change things where you have ownership.

**Comment by marvin9257** [comment]
I'm getting a bunch of errors on my end.  Players can't edit the ship positions.  Also, you need to change the position sheet like so ({{#if}} does not accept multiple arguments.

Screenshot 2023-05-22 at 2 16 09 PM

also, 
```if (foundMacros && foundMacros[0].canExecute()) {```
foundMacros[0] is coming up undefined and causing an error if it can't find the macro.  
Thanks!

I'll let you make the appropriate changes to update.

**Comment by marvin9257** [comment]
I pushed a few more fixes -
some missing localization
setting context for component select
canExecute is a getter, so canExecute() throws error.

Still some more to go.  Maybe allow component select to also work for component actions and get rid of big list at bottom?

**Comment by marvin9257** [comment]
Note...I moved this PR onto the v11 code-base

**Comment by Kampfzwerg42** [comment]
> Still some more to go. Maybe allow component select to also work for component actions and get rid of big list at bottom?

I created a commit that removes that big list and allows to use components for Skillrolls, Fire weapons & the new macro functionality

**Pull request merged**
