### PR TITLE
fix: bugFix-non-characteristic-skill

### PR DESCRIPTION
**Pull request by Kampfzwerg42**
* **Please check if the PR fulfills these requirements**
- [ ] We use semantic versioning (https://github.com/semantic-release/semantic-release to be specific), so follow https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by marvin9257** [comment]
I don't think this works now if there is an attribute.  I think the '/' needs to be added right after the skill name.

**Comment by Kampfzwerg42** [comment]
You are right I fixed it.

**Comment by marvin9257** [comment]
Thank you very much!  I rolled this change into #1239 to fix the RegEx.  Also, it would be easier for me if you merge update your branch to the upstream/master.  There were a bunch of commits that were missing and I got lost.  That is why I started a new PR.

**Comment by marvin9257** [comment]
merged into #1239 so will close this branch.  Thanks!

**Pull request closed without merging**
